feat: ✨ password change UI
AI-READI/fairhub.io pull request #30
Opened 2023-12-12 23:37 UTC by slugb0t

The password that auto fills in develop has been changed to match the same password created by pytest.

2023-12-20 21:30 UTC, megasanjay requested changes
Added comments

2023-12-20 21:30 UTC, megasanjay commented on src/views/account/UserProfile.vue
> +      return true;
Add a validator rule to ensure that the new password is not the same as the old password

2023-12-20 21:30 UTC, megasanjay commented on src/views/account/UserProfile.vue
> +      }
logout on a successful password change. You can just navigate to /auth/logout for this

2023-12-20 21:30 UTC, megasanjay commented on src/views/account/UserProfile.vue
> +      }
Maybe add a notification/message and then delay the navigation to logout for about 1.5 seconds

2023-12-21 21:14 UTC, megasanjay approved these changes

2023-12-21 21:15 UTC, megasanjay commented
@slugb0t Can you double check on this conflict

2023-12-29 05:46 UTC, slugb0t commented
> @slugb0t Can you double check on this conflict

Conflict resolved 👍🏽

2023-12-29 10:05 UTC, megasanjay approved these changes

2023-12-29 10:05 UTC, merged